### ISSUE TITLE
Other distribution channel for aurora-prover besides Docker

### ISSUE THREAD

**Issue by marijanp** [btq-ag/keelung#21]
Hi, is there a way to compile or obtain the aurora-prover binary without using docker?

**Comment by banacorn** [comment]
Sorry, I'm afraid that's not possible at the moment. 
That Dockerized Aurora is a closed-sourced fork intended for ZK research & experiments, we later realized that it may not be a good idea to provide it as a proving system of choice for Keelung.

But we are now working on integrating with Snarkjs/Circom, that means we will be able to use provers like Groth16 in the future.

**Comment by marijanp** [comment]
It has to be possible to run binaries without running/ requiring a whole system image.
